first_name = input('Enter your first name')
last_name = input('Enter your last name')
email= input('Enter your email address')
phone_number = input('Enter your phone number')
job_title = input('Enter your job title')
ID_number = input('Enter your ID number')
hair_color = input('Enter the color of your hair')
eyes_color = input('Enter the color of your eyes')
month = input('Enter your birth month')
training = input('Enter yes/no if you are trained')
print('----------------------------------------')
print(f'{last_name.upper()}, {first_name}')
print(f'{job_title.title()}')
print(f'ID: {ID_number}')
print()
print(f'{email.lower()}')
print(f'{phone_number}')
print(f'Hair:  {hair_color}    Eyes: {eyes_color}')
print(f'Month: {month}      Training:{training}')
print('----------------------------------------')